/*
 * Copyright (C) 2019 Nathan Crause <nathan@crause.name>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package db;

import org.apache.empire.commons.Options;
import org.apache.empire.data.DataMode;
import org.apache.empire.data.DataType;
import org.apache.empire.db.DBTable;
import org.apache.empire.db.DBTableColumn;

/**
 *
 * @author Nathan Crause <nathan@crause.name>
 */
public class Snaps extends DBTable {
	
	public DBTableColumn id;
	public DBTableColumn dateCreated;
	public DBTableColumn targetUrl;
	public DBTableColumn via;
	public DBTableColumn photo;
	
	public Snaps(Database db) {
		super("snaps", db);
		
		id = addColumn("id", DataType.AUTOINC, 0, true, DataMode.AutoGenerated);
		dateCreated = addColumn("date_created", DataType.DATETIME, 0, false);
		targetUrl = addColumn("target_url", DataType.CLOB, 4096, true);
		via = addColumn("via", DataType.TEXT, 255, true);
		photo = addColumn("photo", DataType.BLOB, 0, false);
		
		setPrimaryKey(id);
		
		Options viaOptions = new Options();
		
		viaOptions.set("web", "Web Interface");
		viaOptions.set("api", "API");
		
		via.setOptions(viaOptions);
	}
	
}
